function assert_display_fits(screen_w_px, screen_h_px, board_w_px, board_h_px, reserved_h_px, detail)
%ASSERT_DISPLAY_FITS Ensure board + reserved UI area fits safely.

max_board_w = floor(screen_w_px * 0.95);
max_board_h = floor((screen_h_px - reserved_h_px) * 0.95);

if board_w_px > max_board_w || board_h_px > max_board_h
    msg = sprintf(['棋盘无法安全显示。\n' ...
        '屏幕分辨率: %dx%d px\n' ...
        '物理尺寸: %.2f x %.2f cm\n' ...
        '观察距离: %.2f cm\n' ...
        '格子视角: %.2f deg\n' ...
        '棋盘尺寸: %dx%d px\n' ...
        '最大可用区域(近似): %dx%d px\n' ...
        '建议：减小 cell_deg 或调整 viewing_distance_cm。'], ...
        screen_w_px, screen_h_px, ...
        detail.screen_w_cm, detail.screen_h_cm, ...
        detail.distance_cm, detail.cell_deg, ...
        board_w_px, board_h_px, max_board_w, max_board_h);
    error('DisplayError:BoardTooLarge', '%s', msg);
end
end
